import os
import pathlib
import tempfile
from unittest.mock import MagicMock, patch

import pytest

from builder_agent import config
from builder_agent.plugin_system.base import (
    GenerationContext,
    PluginContext,
    PluginVerificationResult,
)
from builder_agent.plugin_system.builtins import LinterPlugin
from builder_agent.plugin_system.manager import PluginManager
from builder_agent.schemas import Spec, SubTask


# Mock Plugin classes
class MockGeneratorPlugin:
    def generate(
        self, gen_context: GenerationContext, context: PluginContext, on_chunk=None
    ) -> str | None:
        if gen_context.feedback == "fail":
            raise ValueError("Test generation error")
        if gen_context.subtask_id == "custom":
            return "generated by plugin"
        return None


class MockPostProcessorPlugin:
    def post_process_subtask(
        self, subtask: SubTask, code: str, context: PluginContext
    ) -> str:
        if subtask.id == "error_subtask":
            raise ValueError("Post processor error")
        return code + "\n# processed subtask"

    def post_process_artifact(
        self, spec: Spec, code: str | dict[str, str], context: PluginContext
    ) -> str | dict[str, str]:
        if spec.description == "error_artifact":
            raise ValueError("Artifact post processor error")
        if isinstance(code, str):
            return code + "\n# processed artifact"
        return code


class MockVerifierPlugin:
    def verify(
        self, subtask: SubTask, code: str | dict[str, str], context: PluginContext
    ) -> PluginVerificationResult | None:
        if subtask.id == "crash_verifier":
            raise ValueError("Verifier plugin error")
        if subtask.id == "fail_blocking":
            return PluginVerificationResult(
                passed=False, issues=["linter error"], blocking=True
            )
        if subtask.id == "fail_non_blocking":
            return PluginVerificationResult(
                passed=False, issues=["style warning"], blocking=False
            )
        return PluginVerificationResult(passed=True, issues=[])


# 1. Discovery / registration tests


@pytest.fixture(autouse=True)
def clean_registered_plugins():
    from builder_agent.plugin_system import registered_plugins

    registered_plugins.clear()
    yield
    registered_plugins.clear()


def test_plugin_registration_and_filtering():
    manager = PluginManager()
    # Mock config
    with patch.object(config, "PLUGINS_DISABLED", ["MockVerifierPlugin"]):
        manager._register_plugin_class(
            MockGeneratorPlugin, set(config.PLUGINS_DISABLED)
        )
        manager._register_plugin_class(
            MockVerifierPlugin, set(config.PLUGINS_DISABLED)
        )

        assert len(manager.generators) == 1
        assert isinstance(manager.generators[0], MockGeneratorPlugin)
        # MockVerifierPlugin should have been filtered out
        assert len(manager.verifiers) == 0


def test_decorator_registration():
    from builder_agent.plugin_system import (
        register_generator,
        register_post_processor,
        register_verifier,
        registered_plugins,
    )

    registered_plugins.clear()

    @register_generator
    class DecoratedGen:
        def generate(self, gen_context, context, on_chunk=None):
            return "ok"

    @register_verifier
    class DecoratedVerify:
        def verify(self, subtask, code, context):
            return None

    @register_post_processor
    class DecoratedPost:
        def post_process_subtask(self, subtask, code, context):
            return code

    manager = PluginManager()
    manager.discover_and_register()

    assert any(isinstance(g, DecoratedGen) for g in manager.generators)
    assert any(isinstance(v, DecoratedVerify) for v in manager.verifiers)
    assert any(isinstance(p, DecoratedPost) for p in manager.post_processors)


def test_discovery_entry_point_failure_isolation():
    manager = PluginManager()

    mock_ep = MagicMock()
    mock_ep.name = "broken_ep"
    mock_ep.load.side_effect = ImportError("Cannot load plugin dependency")

    with patch(
        "importlib.metadata.entry_points", return_value=[mock_ep]
    ), patch.object(config, "PLUGINS_DISABLED", []):
        manager.discover_and_register()
        # Should not crash during load, just log error
        assert len(manager.generators) >= 0


def test_local_plugins_discovery_and_failure_isolation():
    # Setup temporary directory for local plugins
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create a valid local plugin py file
        valid_plugin = """
class LocalGenPlugin:
    def generate(self, gen_context, context, on_chunk=None):
        return "local code"
"""
        # Create an invalid local plugin py file (contains syntax error)
        invalid_plugin = """
class InvalidPlugin:
    def generate(self, gen_context, context, on_chunk=None)
        return "oops"
"""
        pathlib.Path(tmpdir).mkdir(parents=True, exist_ok=True)
        with open(os.path.join(tmpdir, "valid.py"), "w", encoding="utf-8") as f:
            f.write(valid_plugin)
        with open(os.path.join(tmpdir, "invalid.py"), "w", encoding="utf-8") as f:
            f.write(invalid_plugin)

        manager = PluginManager(plugin_dir=tmpdir)
        with patch.object(config, "PLUGIN_DIR", tmpdir), patch.object(
            config, "PLUGINS_DISABLED", []
        ):
            manager.discover_and_register()

            # Should discover LocalGenPlugin and bypass/log the invalid syntax file
            assert any(
                g.__class__.__name__ == "LocalGenPlugin" for g in manager.generators
            )


# 2. Generator plugins tests


def test_generator_plugin_bypass_and_fallback():
    manager = PluginManager()
    manager.generators.append(MockGeneratorPlugin())

    gen_ctx = GenerationContext(
        subtask_id="custom",
        subtask_description="Custom generation",
        acceptance_criteria=[],
        spec_request="",
        spec_description="",
    )
    context = PluginContext(workspace_dir=".", output_type="python")

    # If plugin returns code, use it
    code = manager.run_generators(gen_ctx, context)
    assert code == "generated by plugin"

    # If plugin returns None, fallback to default (manager returns None)
    fallback_ctx = GenerationContext(
        subtask_id="normal",
        subtask_description="Normal generation",
        acceptance_criteria=[],
        spec_request="",
        spec_description="",
    )
    code2 = manager.run_generators(fallback_ctx, context)
    assert code2 is None


def test_generator_plugin_exception_isolation():
    manager = PluginManager()
    manager.generators.append(MockGeneratorPlugin())

    gen_ctx = GenerationContext(
        subtask_id="normal",
        subtask_description="Normal generation",
        acceptance_criteria=[],
        spec_request="",
        spec_description="",
        feedback="fail",
    )
    context = PluginContext(workspace_dir=".", output_type="python")

    # Should log error and return None (fallback) instead of crashing
    code = manager.run_generators(gen_ctx, context)
    assert code is None


# 3. Post-processor tests


def test_subtask_post_processors():
    manager = PluginManager()
    manager.post_processors.append(MockPostProcessorPlugin())

    subtask = SubTask(id="subtask1", description="desc", acceptance_criteria=[])
    context = PluginContext(workspace_dir=".", output_type="python")

    code = manager.run_subtask_post_processors(subtask, "def foo(): pass", context)
    assert code == "def foo(): pass\n# processed subtask"


def test_artifact_post_processors():
    manager = PluginManager()
    manager.post_processors.append(MockPostProcessorPlugin())

    spec = Spec(
        request="req",
        description="desc",
        acceptance_criteria=[],
        assumptions=[],
        output_type="python",
    )
    context = PluginContext(workspace_dir=".", output_type="python")

    code = manager.run_artifact_post_processors(spec, "integrated code", context)
    assert code == "integrated code\n# processed artifact"


def test_post_processor_exception_isolation():
    manager = PluginManager()
    manager.post_processors.append(MockPostProcessorPlugin())

    subtask = SubTask(id="error_subtask", description="desc", acceptance_criteria=[])
    context = PluginContext(workspace_dir=".", output_type="python")

    # Should return original code without crashing
    code = manager.run_subtask_post_processors(subtask, "original", context)
    assert code == "original"


# 4. Verifier plugins tests


def test_verifier_plugin_merges_issues_and_blocking_fail():
    manager = PluginManager()
    manager.verifiers.append(MockVerifierPlugin())

    subtask = SubTask(id="fail_blocking", description="desc", acceptance_criteria=[])
    context = PluginContext(workspace_dir=".", output_type="python")

    with patch.object(config, "PLUGINS_DISABLED", ["LinterPlugin"]):
        results = manager.run_verifiers(subtask, "code", context)
    assert len(results) == 1
    assert not results[0].passed
    assert results[0].blocking
    assert "linter error" in results[0].issues


def test_verifier_plugin_non_blocking_fail():
    manager = PluginManager()
    manager.verifiers.append(MockVerifierPlugin())

    subtask = SubTask(
        id="fail_non_blocking", description="desc", acceptance_criteria=[]
    )
    context = PluginContext(workspace_dir=".", output_type="python")

    with patch.object(config, "PLUGINS_DISABLED", ["LinterPlugin"]):
        results = manager.run_verifiers(subtask, "code", context)
    assert len(results) == 1
    assert not results[0].passed
    assert not results[0].blocking
    assert "style warning" in results[0].issues


def test_verifier_plugin_exception_isolation():
    manager = PluginManager()
    manager.verifiers.append(MockVerifierPlugin())

    subtask = SubTask(id="crash_verifier", description="desc", acceptance_criteria=[])
    context = PluginContext(workspace_dir=".", output_type="python")

    # Should return empty results and log instead of crashing
    with patch.object(config, "PLUGINS_DISABLED", ["LinterPlugin"]):
        results = manager.run_verifiers(subtask, "code", context)
    assert len(results) == 0


# 5. Built-in Linter Plugin tests


def test_linter_plugin_unsupported_language_skip():
    plugin = LinterPlugin()
    context = PluginContext(workspace_dir=".", output_type="sql")
    subtask = SubTask(id="sql_check", description="desc", acceptance_criteria=[])

    res = plugin.verify(subtask, "SELECT * FROM users;", context)
    assert res.passed
    assert not res.blocking
    assert "Skipping linter for unsupported output type" in res.exec_output


@patch("subprocess.run")
def test_linter_plugin_ruff_success(mock_run):
    mock_run.return_value = MagicMock(returncode=0, stdout="All clear", stderr="")

    plugin = LinterPlugin()
    context = PluginContext(workspace_dir=".", output_type="python")
    subtask = SubTask(id="py_check", description="desc", acceptance_criteria=[])

    res = plugin.verify(subtask, "def main(): pass", context)
    assert res.passed
    assert res.blocking
    assert "All clear" in res.exec_output


@patch("subprocess.run")
def test_linter_plugin_ruff_failure(mock_run):
    mock_run.return_value = MagicMock(
        returncode=1, stdout="code.py:1:1: E901 SyntaxError", stderr=""
    )

    plugin = LinterPlugin()
    context = PluginContext(workspace_dir=".", output_type="python")
    subtask = SubTask(id="py_check", description="desc", acceptance_criteria=[])

    res = plugin.verify(subtask, "def main() pass", context)
    assert not res.passed
    assert res.blocking
    assert "code.py:1:1: E901 SyntaxError" in res.issues


@patch("subprocess.run")
def test_linter_plugin_eslint_success(mock_run):
    mock_run.return_value = MagicMock(returncode=0, stdout="No errors", stderr="")

    plugin = LinterPlugin()
    context = PluginContext(workspace_dir=".", output_type="javascript")
    subtask = SubTask(id="js_check", description="desc", acceptance_criteria=[])

    res = plugin.verify(subtask, "const a = 1;", context)
    assert res.passed
    assert res.blocking
    assert "No errors" in res.exec_output


@patch("subprocess.run")
def test_linter_plugin_eslint_failure(mock_run):
    mock_run.return_value = MagicMock(
        returncode=1, stdout="Unexpected var keyword", stderr=""
    )

    plugin = LinterPlugin()
    context = PluginContext(workspace_dir=".", output_type="javascript")
    subtask = SubTask(id="js_check", description="desc", acceptance_criteria=[])

    res = plugin.verify(subtask, "var x = 2;", context)
    assert not res.passed
    assert res.blocking
    assert "Unexpected var keyword" in res.issues


@patch("subprocess.run")
def test_linter_plugin_missing_executable(mock_run):
    mock_run.side_effect = FileNotFoundError()

    plugin = LinterPlugin()
    context = PluginContext(workspace_dir=".", output_type="python")
    subtask = SubTask(id="py_check", description="desc", acceptance_criteria=[])

    res = plugin.verify(subtask, "print('hello')", context)
    # Should skip gracefully
    assert res.passed
    assert not res.blocking
    assert "Ruff executable not found. Skipped python linting." in res.exec_output


@patch("subprocess.run")
def test_linter_plugin_multi_file_python_package(mock_run):
    mock_run.return_value = MagicMock(returncode=0, stdout="All clear", stderr="")

    plugin = LinterPlugin()
    context = PluginContext(workspace_dir=".", output_type="python_package")
    subtask = SubTask(id="py_check", description="desc", acceptance_criteria=[])

    files = {"src/__init__.py": "", "src/main.py": "print('hello')"}

    res = plugin.verify(subtask, files, context)
    assert res.passed
    assert res.blocking
    assert "All clear" in res.exec_output


# 6. E2E / Integration tests for generate/verify hooks in orchestrate.py


@patch("builder_agent.generate.ask")
@patch("builder_agent.verify.ask")
@patch("builder_agent.verify.run_code")
def test_subtask_hooks_composition_in_verify_and_generate(
    mock_run_code, mock_verify_ask, mock_ask
):
    # Setup mocks
    mock_ask.return_value = "def hello():\n    return 'world'"
    mock_verify_ask.return_value = '{"score": 9, "issues": []}'
    mock_run_code.return_value = (True, "all tests passed")

    # Prepare plugin manager with Custom Generator
    manager = PluginManager()
    manager.generators.append(MockGeneratorPlugin())
    manager.post_processors.append(MockPostProcessorPlugin())
    manager.verifiers.append(MockVerifierPlugin())

    subtask = SubTask(id="custom", description="desc", acceptance_criteria=[])
    spec = Spec(
        request="req",
        description="desc",
        acceptance_criteria=[],
        assumptions=[],
        output_type="python_module",
    )

    # 1. Test generate integration
    from builder_agent.generate import generate

    code = generate(subtask, spec, plugin_manager=manager)
    # Bypassed default generate block entirely and returned custom code
    assert code == "generated by plugin"

    # 2. Test verify integration with blocking failure
    from builder_agent.verify import verify

    bad_subtask = SubTask(
        id="fail_blocking", description="desc", acceptance_criteria=[]
    )
    with patch.object(config, "PLUGINS_DISABLED", ["LinterPlugin"]):
        verdict = verify(
            bad_subtask,
            "code",
            output_type="python_module",
            plugin_manager=manager,
        )
    # Merged issues and forced passed=False
    assert not verdict.passed
    assert "linter error" in verdict.issues
